apiVersion: v1
data:
  nic_name: "bond2" # 填写需要与交换机建立ospf邻居的网卡名称，使用默认路由所在网卡时填写空字符串 ""
  gateway: "192.168.0.1" # 填写交换机地址，不填将自动探查
  neighbor_network: "192.168.0.0/24" # 填写网络的CIDR
kind: ConfigMap
metadata:
  name: quagga-ospf-cfg
  namespace: kube-system

---

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: quagga
  name: quagga
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: quagga
  template:
    metadata:
      labels:
        k8s-app: quagga
      name: quagga
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: qiniu.com/calico-tlb-role
                operator: In
                values:
                - director
      containers:
      - args:
        - /etc/quagga/change_quagga_config.sh
        command:
        - /bin/bash
        env:
          - name: _NIC_NAME_
            valueFrom:
              configMapKeyRef:
                 name: quagga-ospf-cfg
                 key: nic_name
          - name: _GATEWAY_
            valueFrom:
              configMapKeyRef:
                 name: quagga-ospf-cfg
                 key: gateway
          - name: _NEIGHBOR_
            valueFrom:
              configMapKeyRef:
                 name: quagga-ospf-cfg
                 key: neighbor_network           
        image: reg.kpaas.io/kpaas/quagga:v1.3.6
        imagePullPolicy: Always
        name: quagga
        securityContext:
          privileged: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: calico-tlb-director
  updateStrategy:
    type: OnDelete
